exclude: ^misc/bench.py$
repos:
-   repo: https://github.com/asottile/seed-isort-config
    rev: v1.9.1
    hooks:
    - id: seed-isort-config
-   repo: https://github.com/timothycrosley/isort
    rev: 4.3.21
    hooks:
    - id: isort
      args:
          - "--filter-files"
-   repo: https://github.com/ambv/black
    rev: 19.3b0
    hooks:
    - id: black
      args:
          - "--line-length=100"
          - "--exclude=parsec/core/gui/_resources_rc.py"
          - "--exclude=parsec/core/gui/ui/"
      language_version: python3
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.7
    hooks:
    - id: flake8
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3  # Use the ref you want to point at
    hooks:
    - id: mixed-line-ending
    - id: trailing-whitespace
-   repo: local
    hooks:
    - id: releaser
      name: releaser
      entry: python ./misc/releaser.py check
      language: python
      language_version: python3
      pass_filenames: false
      require_serial: true
    - id: license_headers
      name: license_headers
      entry: python ./misc/license_headers.py add
      language: python
      language_version: python3
      types: [python]
