sudo: required
language: python
python:
- '3.6'
#- '3.7-dev'

addons:
  apt:
    packages:
    - postgresql-10
    - postgresql-server-dev-10
    - desktop-file-utils

env:
  global:
  - PGINSTALLATION=/usr/lib/postgresql/10/bin

install:
# Update packaging packages
- pip install -U wheel pip setuptools
# Workaround a compatibility issue by pre-installing requests
- pip install requests
# Build the parsec wheel
- python setup.py bdist_wheel
# Install the parsec wheel with all dependencies
- pip install $(ls dist/parsec_cloud-*.whl)[all]
# Check dependency compatibility
- pip check parsec[all]

before_script:
- sudo modprobe fuse

script:
- set -e  # stop build as soon as a command fails
- git fetch --tags  # Needed by releaser.py to have a consistent `git describe`
- python ./misc/releaser.py check --verbose
# Only print output if check failed
- OUT=$(2>&1 ./misc/autoformat.sh --check) || (echo $OUT; $(exit 1))
- flake8 setup.py parsec tests
- python ./misc/license_headers.py check
- mkdir empty && cd empty
- sed -i 's#omit = \(.*\)#omit = \1,../\1#' ../setup.cfg  # fix path
# Run everything with memory driver
- py.test ../tests/ --runmountpoint --runslow -n 2 --max-worker-restart=0  --log-level=DEBUG -vvv -x --cov=parsec --cov-config=../setup.cfg --cov-append
# Run backend tests with postgresql driver
- py.test ../tests/backend ../tests/test_cli.py --postgresql --runslow -n 2 --max-worker-restart=0  --log-level=DEBUG -vvv -x --cov=parsec --cov-config=../setup.cfg --cov-append
# The GUI tests fail on travis for some reason, even with the xvfb service
# - py.test ../tests/ -m gui --runmountpoint --runslow --rungui -vvv -x --log-level=DEBUG --cov=parsec --cov-config=../setup.cfg --cov-append
- set +e

after_success:
- pip install -U codecov
- codecov

before_deploy:
- cd $TRAVIS_BUILD_DIR

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: touilleMan
  password:
    secure: jKO3OqR3aPBMjeQAJ78IFN13ffFHG67pbWw851S/PyTkYTsQht985EmGDNBWqwzVzx7X1+uKyso5Rogjo1rpezHCTj7F016PUzawegx/4ujbt+pGFq1wN3wIpW9z6IygT769enV9I5WQ7/42AWNi5Zzs3+atEj3MT+LMqd0g80DvoxZmrRC3Imn3hDzG3oskA1I2VGELzvFkrLDfocXxsUmMiLkmvUBM/2T5Nf2LUdH/bSX+gnifYQwbjfkCKs0rfkLsTYSFA722UrP+lhZkj4H0N0laj0OoDMBREB4qnWaaMgNPrbv1mn3oI+sju6Oe97xLislj6ZxN5LOGmpRcXM5QYtSE8oWupvNQc5eTm9DFmy8/IYy0dbty0dTxI7OWssgLW7KKKjrrXARrNQaFoeOAR9jCRV0kK3l4e7xvvg0EFoyi9LCLkYKSU7cfe01cJzJIQHskTfKiO/KAiWTvSE44Upsf8gmwgPffttDkrb75adm8huXilCro/ICB2TSPTj8UnYaZkPas92anztdxlmIC8beFakR0JdjhniXrNk9aaRG0+NCK8oZx6lv4WwOcWkePE7HhGlVEDTNmI4uwdmLhbKv1UK5zfMzIHyPRD++e4SLINUweAFU6rQ38zVTq1C6N6+IEv1r9f6ecBL3ij+y+N+eeGztlkA1MqCrJRLU=
  on:
    tags: true
    repo: Scille/parsec-cloud
    python: 3.6
